import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-4xl mx-auto p-4">
          <Navbar />
          {children}
          <footer className="border-t p-8 text-center mt-16 bg-gray-50">
            &copy; 2024 All rights reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
